# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-18 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_competition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='file',
        ),
        migrations.AddField(
            model_name='competition',
            name='submission',
            field=models.TextField(default=b''),
        ),
    ]
